apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jgaf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-jgaf@sha256:8879ffefe4abe0635395b8ffafe3fdf444d8f952b7564d290cbf5aac5fb94a6f
        name: my-nodejs
        resources: {}
status: {}
